eggplant/eggplant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

#from polls.admin import admin_site

# Namespcae
# The namespace is added to the include(). It is clearer
# to add namespace in include() because it can be seen
# in one glance this include file is associated with this
# namespace.
urlpatterns = [
    # default admin
    path(route='admin/', view=admin.site.urls),
    # django_browser_reload
    path(route="__reload__/", 
         view=include("django_browser_reload.urls")),
    # index homepage
    path(route="polls/", 
         view=include("polls.urls", namespace="polls")),
    # custom admin
    #path("eggplant_admin/", admin_site.urls, name="eggplant_admin"),   
]


# Only serve uploaded files this way if you are in DEBUG=True mode.
# Add the new route returned by static() into urlpatterns.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, 
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, 
                          document_root=settings.STATIC_ROOT)

eggplant/polls/urls.py
# polls/urls.py

from django.urls import path

from polls import views as polls_views

# Namespace
# Declare the app_name here and also specify the namespace
# in the urls of the include() file.
app_name = "polls"

# URLs
urlpatterns = [
     # homepage: /polls/
     path("", polls_views.index, 
         name="index"),
     # display list the questions--all questions
     path("question_list/", polls_views.question_list,
          name="question_list"),
     # display only the latest 5 questions
     path("question_list_recent/", polls_views.question_list_recent,
          name="question_list_recent"),
     # detail of question: /polls/5
     path("question_detail/<int:question_id>/", 
          polls_views.question_detail, 
         name="question_detail"),
     # vote for a question, display the detail of a question
     path("question_vote/<int:question_id>/",
          polls_views.question_vote,
          name="question_vote"),
     # vote on a question: /<int:question_id>/vote/
     # this is used in the from action="polls:vote question.id"
     path("<int:question_id>/vote/", polls_views.vote, 
         name="vote"),
     # results of a question: /<int:question_id>/results/
     path("<int:question_id>/vote_results/", polls_views.vote_results, 
         name="vote_results"),
     # htmx pages, use the same question_list view for the 
     # beginning link
     path("question_list_htmx/", polls_views.question_list_htmx,
          name="question_list_htmx"),
     # using htmx to display a question in the top homepage
     path("choices_partial/", polls_views.choices_partial,
          name="choices_partial"),
     # partial question to be loaded into the question list above
     path("question_partial", polls_views.question_partial,
          name="question_partial"),
     # search results
     path("search_results/", polls_views.search_results,
          name="search_results"),
     # click-to-edit
     path("question_list_edit/", polls_views.question_list_edit,
          name="question_list_edit"),
     # form for the click-to-edit
     path("edit_question_form/<int:question_id>/", polls_views.edit_question_form,
          name="edit_question_form"),
]

eggplant/polls/models.py
from django.db import models
from django.contrib import admin

# other libraries
from datetime import date, datetime, timedelta

# app libraries

# Create your models here.



# A Question has a question and a publication date. 
# A Choice has two fields: the text of the choice 
# and a vote tally. 
# Each Choice is associated with a Question.
class Question(models.Model):
    """Question model"""
    id = models.SmallAutoField(primary_key=True)
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField(verbose_name="date published")
    
    class Meta:
        # order by latest pub_date
        ordering = ["-pub_date"]

    # decorator for was_published_recently
    # need to use: from django.contrib import admin
    @admin.display(boolean=True, ordering="pub_date", description="Recently added")
    def was_published_recently(self) -> bool:
        """Whether the publication date is recent or not."""
        # Recent is true when the question is published within 7 days,
        # publication date cannot be in future date
        recent = False
        if (
            (datetime.today() - timedelta(days=7)) <= self.pub_date \
              <= datetime.today()
           ):
            recent = True
        return recent

    def __str__(self):
        """Return only up to 30 chars"""
        return f"Question {self.id}, {self.question_text[:30]}"

class Choice(models.Model):
    """Choice model."""
    id = models.SmallAutoField(primary_key=True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    class Meta:
        # order by question id, then choice id
        ordering = ["question", "id"]

    def __str__(self):
        """Return the Choice"""
        return f"Choice {self.id}, {self.choice_text[:30]}"

eggplant/polls/forms.py
# forms for polls app

from django import forms
from polls.models import Question, Choice

class QuestionForm(forms.Form):
    model = Question
    fields = ["question_text"]

eggplant/polls/views.py
from django.shortcuts import render, redirect
from django.shortcuts import get_list_or_404, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
# using F() to query database
from django.db.models import F
# Create your views here.
from polls.models import Question, Choice

def index(request):
    """Polls homepage"""
    template = loader.get_template("polls/index.html")
    context = {
        "title": "Home"
    }
    return HttpResponse(template.render(context, request))

def question_list_recent(request, recent=None):
    """List of questions"""
    # check for display all question or only recent question
    print(f"\t{request=}")
    print(f"\t{request.POST.get('recent')=}")
    # latest question only
    # request.POST.get('recent')='1'
    if request.POST.get("recent") == "on":
        latest_question_list = Question.objects.order_by("-pub_date")[:2]
    else:
        # request.POST.get('recent')=None
        # all questions
        latest_question_list = Question.objects.order_by("-pub_date")
    
    template = loader.get_template("polls/question_list_recent.html")
 
    context = {
        "title": "Question list",
        "latest_question_list": latest_question_list,
    }
    return HttpResponse(template.render(context, request))


def question_list(request, recent=None):
    """List of questions"""
    # all questions
    latest_question_list = Question.objects.order_by("-pub_date")
    
    template = loader.get_template("polls/question_list.html")
    context = {
        "title": "Question list",
        "latest_question_list": latest_question_list,
    }
    return HttpResponse(template.render(context, request))


def question_detail(request, question_id):
    """Detail of a question"""
    question = get_object_or_404(Question, id=question_id)
    template = loader.get_template("polls/question_detail.html")
    context = {
        "title": "Question detail",
        "question": question,
    }
    return HttpResponse(template.render(context, request))


def question_vote(request, question_id):
    """Vote for a question, similar to detail of a question.
       But this view has a vote button.
    """
    question = get_object_or_404(Question, id=question_id)
    template = loader.get_template("polls/question_vote.html")
    context = {
        "title": "Question vote",
        "question": question,
    }
    return HttpResponse(template.render(context, request))


def vote(request, question_id):
    """User click on the vote button to vote"""
    question = get_object_or_404(Question, id=question_id)
    try:
        # Get the user's choices
        selected_choice = question.choice_set.get(
            id=request.POST["choice"]
        )
        #print(f"\t{selected_choice=}")
    except(KeyError, Choice.DoesNotExist): 
        # Mapping key not found
        # Redisplay the question voting form
        return render(request=request,
                      template_name="polls/question_vote.html",
                      context = {
                           "title": "Voting",
                           "question": question,
                           "error_message": "You did not select a choice."
                      })
    else:
        # Using F() to directly use the database query
        print(f"\tIn vote: current votes: {selected_choice.votes}")
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        # After save, we have to retrieve the object again to get
        # the latest state of the db.
        selected_choice = Choice.objects.get(id=selected_choice.id)
        print(f"\tIn vote: after votes: {selected_choice.votes}")
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        # return HttpResponseRedirect(
        #     reverse("polls:results", args=(question.id,))
        # )
        return HttpResponseRedirect(
            reverse("polls:vote_results", args=(question.id, ))
        )


def vote_results(request, question_id):
    """Display the results of a vote"""
    question = get_object_or_404(Question, id=question_id)
    context = {
        "title": "Results",
        "question": question,
    }
    return render(request=request, 
                  template_name="polls/vote_results.html",
                  context=context)


# HTMX tutorial
def question_list_htmx(request):
    """Display question using htmx"""
    context = {"title": "List HTMX" }
    return render(request=request, 
                  template_name="polls/question_list_htmx.html", 
                  context=context)

import time
def question_partial(request):
    """Partial question to be loaded by HTMX"""
    time.sleep(2) # 2 sec: to simulate lazy loading
    context = {
        "title": "Partial questions",
        "questions": Question.objects.all(),
    }
    return render(request=request,
                  template_name="polls/partials/question_list_partial.html",
                  context=context
                )


def choices_partial(request, question_id):
    """Display detail of question using htmx"""
    context = {
        "some_text": question_id,
    }
    return render(request=request,
                  template_name="polls/partials/choices_partial.html",
                  context=context)

# For searching questions
from django.db.models import Q
import urllib

def search_results(request):
    """Search question from the keywords given by users"""
    search_text = request.GET.get("search_text", "")
    # print(f"Request: {request}")
    # A URL param was encoded. Turn it back into a regular
    # string.
    # print(f"\tBefore unquoting: {search_text}")
    # Actually there is no need to unquote, because the
    # request will return unquotedly strings automatically.
    search_text = urllib.parse.unquote_plus(search_text, encoding='utf-8')
    # print(f"\tAfter unquoting: {search_text}")
    # make lowercase for case insensitive search
    search_text = search_text.lower() 
    search_text = search_text.strip()

    results = []

    if search_text:
        # split the text into individual terms
        parts = search_text.split()
        # Build a Q objects OR-ed together to search
        # for this term in the questions
        # build the first query term
        q = Q(question_text__icontains=parts[0])
        # if there are more than one search terms
        if len(parts) > 1:
            for x in parts[1:]:
                q |= Q(question_text__icontains=x)
        # Search the Question filter with the query 
        # built with Q.
        results = Question.objects.filter(q)
        # print(f"Search results: {results}")
    
    # compose the context
    context = {
        "title": "Search results",
        "search_text": search_text,
        "results": results
    }
    return render(request=request, template_name="polls/search_results.html",
                  context=context)


def question_list_edit(request):
    """Click-to-edit questions using HTMX"""
    context = {
        "title": "Click-to-edit question",
        "questions": Question.objects.all(),
    }
    return render(request=request, 
                  template_name="polls/question_list_edit.html",
                  context=context)

from polls.forms import QuestionForm

def edit_question_form(request, question_id):
    """Edit form fro the click-to-edit"""
    question = get_object_or_404(Question, id=question_id)

    # POST
    if request.method == "POST":
        # get the instance corresponding to the id
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            form.save()
            context = {"question": question}
            return render(request=request, 
                          template_name="polls/partials/edit_question.html", context=context)

    # GET
    elif request.method == "GET":
        form = QuestionForm(instance=question)
    
    # It is a GET or the form is not valid
    context = {
        "question": question
    }
    return render(request=request, 
                  template_name="polls/edit_question_form.html",
                  context=context)
    

eggplant/polls/templates/polls/edit_question_form.html
<!--edit question form-->
<li id="id_question_{{question.id}}">
    <form>
        {% csrf_token %}
        {{ form.as_p }}
        <button
            hx-post="{% url 'polls/edit_question_form' %}"
            hx-target="#id_question_{{question.id}}"
        >
            Save
        </button>
    </form>
</li>

eggplant/polls/templates/polls/index.html
<!--polls/index.html-->
{% extends "base.html" %}
{% load static %}

{% block title %}
  {{ block.super }} {{ title }}
{% endblock title %}

{% block content %}
  <h1>Eggplant polls</h1>
  <p>
    <ul class="list-group">
        <li class="list-group-item">
          <a href="{% url 'polls:question_list' %}">
            Poll questions</a>
        </li>

        <li class="list-group-item">
          <a href="{% url 'polls:question_list_recent' %}">
            Poll questions recent</a>
        </li>
        
        <!--
        <li class="list-group-item">
          <a href="{% url 'polls:question_list_htmx' %}">
            Display questions using htmx</a>
        </li>

        
        <li class="list-group-item">
          <a href="{% url 'polls:question_list_edit' %}">
            Click-to-edit questions using htmx</a>
        </li>
        -->
      </ul>
  </p>
  <p>
    <h3>Search questions</h3>
    <form class="d-flex" role="search"
      method="GET" action="{% url 'polls:search_results' %}"
    >
      <input class="form-control me-2" type="search" 
      placeholder="Search" aria-label="Search" 
      name="search_text">
      <button class="btn btn-outline-success" type="submit">
        Search
      </button>
    </form>
  </p>
  <div class="row">
    <div class="col-md-2 offset-md-5">
      <img src="{% static 'polls/logo.svg' %}" alt="logo"
       class="img-fluid" width="100%" height=auto>
    </div>
  </div>
{% endblock content %}

eggplant/polls/templates/polls/question_detail.html
<!--polls/index.html-->
{% extends "base.html" %}

{% block title %}
  {{ block.super }} {{ title }}
{% endblock title %}

{% block content %}
  
  {% if question %}
  <h1>Question {{ question.id }}:</h1>

  <p>
    <h3>{{ question.question_text}}</h3>
  </p>

  <p>
    <h2>Choices</h2>
    <ul class="list-group">
        {% for item in question.choice_set.all %}
        <li class="list-group-item">
            {{ item.choice_text }}
        </li>
        {% empty %}
        <li class="list-group-item">No choices in this question.</li>
        {% endfor %}
    </ul>
    </p>
  {% endif %}

  <p>
  <!--back to main listing-->
  <a 
    class="btn btn-primary"
    href="{% url 'polls:question_list' %}"
  >
    Back to questions
  </a>
  <!-- if there are choices -->
  {% if question.choice_set.count > 0 %}
  <a 
    class="btn btn-primary"
    href="{% url 'polls:question_vote' question.id %}"
  >
    I want to vote
  </a>
  {% endif %}
  </p>
{% endblock content %}

eggplant/polls/templates/polls/question_list.html
<!--polls/index.html-->
{% extends "base.html" %}
{% load static %}
{% block title %}
  {{ block.super }} {{ title }}
{% endblock title %}

{% block content %}
  <h1>Poll question</h1>

  <p>Number of questions: {{ latest_question_list.count }}</p>

  <!--Display all question or recent question only-->
  <div class="form-check">
    <!--script defer src="{% static 'question_list.js' %}"-->
    <form id="id_recent_form"
      action="{% url 'polls:question_list' %}" 
      method="POST"
      enctype="application/x-www-form-urlencoded">
      {% csrf_token %}
      <input class="form-check-input" type="checkbox" role="switch"   
        id="id_recent_box" name="recent" value="1">
      <label class="form-check-label" for="id_display">
        List recent questions only</label>
        <button id="id_recent_btn" type="submit">Recent questions</button>
    </form>
    <script defer src="{% static 'polls/question_list.js' %}">
    </script>
  </div>
  

  {% if latest_question_list %}
    <ul class="list-group">
        {% for question in latest_question_list %}
            <li class="list-group-item mt-3">
              {{ question.question_text }}
              <div class="d-flex-inline">
              <a href="{% url 'polls:question_detail' question.id %}"
                class="btn btn-info">
                View detail      
              </a>
              <a href="{% url 'polls:question_vote' question.id %}"
                class="btn btn-primary">
                I want to vote      
              </a>
              </div>
              
            </li>
        {% endfor %}
    </ul>
  {% else %}
    <p>No poll questions are available.</p>
  {% endif %}
{% endblock content %}

eggplant/polls/templates/polls/question_list_edit.html
<!--polls/question_list_edit.html-->
<!--Edit with HTMX-->
{% extends "base.html" %}

{% block title %}
  {{ block.super }} {{ title }}
{% endblock title %}

{% block content %}
  <h1>Poll question</h1>

  <p>Number of questions: {{ questions.count }}</p>

  {% if questions %}
    <ul class="list-group">
        {% for question in questions %}
            <!--li class="list-group-item mt-3"-->
              {% include "polls/partials/edit_question.html" %}
              <div class="d-flex-inline">
              <a href="{% url 'polls:question_detail' question.id %}"
                class="btn btn-info">
                View detail      
              </a>
              <a href="{% url 'polls:question_vote' question.id %}"
                class="btn btn-primary">
                I want to vote      
              </a>
              <!--/div-->
            </li>
        {% endfor %}
    </ul>
  {% else %}
    <p>No poll questions are available.</p>
  {% endif %}
{% endblock content %}

eggplant/polls/templates/polls/question_list_htmx.html
<!--polls/question_list_htmx.html-->
{% extends "base.html" %}

{% block title %}
  {{ block.super }} {{ title }}
{% endblock title %}

{% block content %}
  <h1>Display question with HTMX</h1>

  <div
    hx-get="{% url 'polls:question_partial' %}"
    hx-trigger="load"
  >
    <i>Loading question...</i>
    <div id="id_question_area"></div>
  </div>
{% endblock content %}

eggplant/polls/templates/polls/question_list_recent.html
<!--polls/index.html-->
{% extends "base.html" %}
{% load static %}
{% block title %}
  {{ block.super }} {{ title }}
{% endblock title %}

{% block content %}
  <h1>Poll question</h1>

  <p>Number of questions: {{ latest_question_list.count }}</p>

  <!--Display all question or recent question only-->
  <!--The submit button can work, but the form submission will not work.-->
  <div class="form-check">
    <form id="id_recent_form"
      action="{% url 'polls:question_list_recent' %}"
      method="POST"
      enctype="application/x-www-form-urlencoded">
      {% csrf_token %}
      <input class="form-check-input" type="checkbox" role="switch"   
        id="id_recent_box" name="recent">
      <label class="form-check-label" for="id_display">
        Recent questions only</label>
        <button id="id_recent_btn" type="submit">Submit</button>
    </form>
  </div>
  

  {% if latest_question_list %}
    <ul class="list-group">
        {% for question in latest_question_list %}
            <li class="list-group-item mt-3">
              {{ question.question_text }}
              <div class="d-flex-inline">
              <a href="{% url 'polls:question_detail' question.id %}"
                class="btn btn-info">
                View detail      
              </a>
              <a href="{% url 'polls:question_vote' question.id %}"
                class="btn btn-primary">
                I want to vote      
              </a>
              </div>
              
            </li>
        {% endfor %}
    </ul>
  {% else %}
    <p>No poll questions are available.</p>
  {% endif %}
{% endblock content %}

eggplant/polls/templates/polls/question_list_recent_form.html
<!--polls/index.html-->
{% extends "base.html" %}
{% load static %}
{% block title %}
  {{ block.super }} {{ title }}
{% endblock title %}

{% block content %}
  <h1>Poll question</h1>

  <p>Number of questions: {{ latest_question_list.count }}</p>

  <!--Display all question or recent question only-->
  <div class="form-check">
    <!--script defer src="{% static 'question_list.js' %}"-->
    <form id="id_recent_form"
      action="{% url 'polls:question_list' %}" 
      method="POST"
      enctype="application/x-www-form-urlencoded">
      {% csrf_token %}
      <input class="form-check-input" type="checkbox" role="switch"   
        id="id_recent_box" name="recent" value="1">
      <label class="form-check-label" for="id_display">
        List recent questions only</label>
        <button id="id_recent_btn" type="submit">Recent questions</button>
    </form>
    <script defer src="{% static 'polls/question_list.js' %}">
    </script>
  </div>
  

  {% if latest_question_list %}
    <ul class="list-group">
        {% for question in latest_question_list %}
            <li class="list-group-item mt-3">
              {{ question.question_text }}
              <div class="d-flex-inline">
              <a href="{% url 'polls:question_detail' question.id %}"
                class="btn btn-info">
                View detail      
              </a>
              <a href="{% url 'polls:question_vote' question.id %}"
                class="btn btn-primary">
                I want to vote      
              </a>
              </div>
              
            </li>
        {% endfor %}
    </ul>
  {% else %}
    <p>No poll questions are available.</p>
  {% endif %}
{% endblock content %}

eggplant/polls/templates/polls/question_vote.html
<!--polls/index.html-->
{% extends "base.html" %}

{% block title %}
  {{ block.super }} {{ title }}
{% endblock title %}

{% block content %}
  <h1>Vote</h1>
  
  <form 
    action="{% url 'polls:vote' question.id %}" 
    method="POST"
  >
    {% csrf_token %}
    <fieldset>
      <legend><h1>{{ question.question_text }}</h1></legend>
      
        {% if error_message %}
          <p><strong>{{ error_message }}</strong></p>
        {% endif %}
        
        {% for item in question.choice_set.all %}
            <div class="form-check">
                <input type="radio" name="choice" 
                    id="id_choice_{{ forloop.counter}}" 
                    value="{{ item.id }}"
                    required
                    class="form-check-input">
                <label for="id_choice_{{ forloop.counter }}" 
                    class="form-check-label">
                    {{ forloop.counter }} {{ item.choice_text }}
                </label>
            </div>
        {% empty %}
                <p>No choices for this question.</p>
        {% endfor %}

    </fieldset>
      <!-- if there are choices -->
  {% if question.choice_set.count == 0 %}
  <a 
    class="btn btn-primary"
    href="{% url 'polls:question_list' %}"
  >
    Back to questions
  </a>
  {% else %}
    <button type="submit" class="btn btn-primary">Vote</button>
  {% endif %}
  </form>

{% endblock content %}

eggplant/polls/templates/polls/search_results.html
<!--polls/search_results.html-->
{% extends "base.html" %}

{% block title %}
  {{ block.super }} {{ title }}
{% endblock title %}

{% block content %}
  <h1>Search results</h1>
  <p>Results for <br>
    {{ search_text }}
  </p>

  <ul class="list-group">
    {% for result in results %}
    <li class="list-group-item">
        {{ forloop.counter }}. {{ result.question_text }}
    </li>
    {% empty %}
    <li class="list-group-item">
        No results found.
    </li>
    {% endfor %}
  </ul>

  <a class="btn btn-primary" href="{% url 'polls:index' %}">
    Back
  </a>
{% endblock content %}

eggplant/polls/templates/polls/snippet.html
<!--polls/index.html-->
{% extends "base.html" %}

{% block title %}
  {{ block.super }} {{ title }}
{% endblock title %}

{% block content %}
  <h1></h1>

{% endblock content %}

eggplant/polls/templates/polls/vote_results.html
<!--polls/index.html-->
{% extends "base.html" %}

{% block title %}
  {{ block.super }} {{ title }}
{% endblock title %}

{% block content %}
  <h1>Results to Question</h1>

  <h2>{{ question.question_text }}</h2>

  <!--Table of result-->
  <table class="table table-bordered border-dark table-sm">
    <caption>Results of votes</caption>
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Choice</th>
            <th scope="col">Number of votes</th>
        </tr>
    </thead>
    <tbody class="table-group-divider">
        {% for choice in question.choice_set.all %}
        <tr>
            <th scope="row">{{ forloop.counter }}
            <td>{{ choice.choice_text }}</td>
            <td>{{ choice.votes }}</td>
        </tr>
        {% empty %}
        <tr span="3">
            No choices for this question.
        </tr>
        {% endfor %}
    </tbody>
  </table>

  <!--Vote again button-->
  <p>
    <a class="btn btn-primary"
        href="{% url 'polls:question_vote' question.id %}">
        Vote again?
    </a>
    <a class="btn btn-primary"
    href="{% url 'polls:question_list' %}">
    Back to questions
</a>
  </p>
{% endblock content %}